# Generated by Django 5.2.17 on 2026-08-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('input_type', models.CharField(choices=[('story', 'Story'), ('script', 'Script')], default='story', max_length=20)),
                ('prompt', models.TextField()),
                ('aspect_ratio', models.CharField(default='9:16', max_length=10)),
                ('duration', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('provider', models.CharField(default='json2video', max_length=50)),
                ('provider_project_id', models.CharField(blank=True, max_length=100, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
