# Generated by Django 5.2.17 on 2026-09-01 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_workspaces(apps, schema_editor):
    from django.conf import settings
    user_app, user_model_name = settings.AUTH_USER_MODEL.split(".") if "." in settings.AUTH_USER_MODEL else ("auth", "User")
    User = apps.get_model(user_app, user_model_name)
    Workspace = apps.get_model('video_generator', 'Workspace')
    WorkspaceMembership = apps.get_model('video_generator', 'WorkspaceMembership')
    VideoProject = apps.get_model('video_generator', 'VideoProject')

    for user in User.objects.all():
        workspace = Workspace.objects.filter(owner=user, is_personal=True).first()
        if not workspace:
            workspace = Workspace.objects.create(
                owner=user,
                name=f"{user.username}'s Workspace",
                is_personal=True,
            )
        WorkspaceMembership.objects.get_or_create(
            workspace=workspace,
            user=user,
            defaults={'role': 'owner'},
        )
        VideoProject.objects.filter(user=user, workspace__isnull=True).update(workspace=workspace)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('video_generator', '0010_emailverificationtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_personal', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='videoproject',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='video_generator.workspace'),
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], db_index=True, default='viewer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='video_generator.workspace')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'user'), name='unique_workspace_membership')],
            },
        ),
        migrations.RunPython(backfill_workspaces, noop_reverse),
    ]

