# Generated by Django 5.2.17 on 2026-09-01 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_generator', '0011_workspace_videoproject_workspace_workspacemembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditaccount',
            name='workspace',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_pool', to='video_generator.workspace'),
        ),
        migrations.AlterField(
            model_name='creditaccount',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_code',
            field=models.CharField(choices=[('free', 'Free'), ('creator', 'Creator'), ('pro', 'Pro'), ('studio', 'Studio'), ('enterprise', 'Enterprise')], default='free', max_length=30),
        ),
    ]
