# Generated by Django 5.2.17 on 2026-09-01 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_generator', '0012_creditaccount_workspace_alter_creditaccount_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoproject',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='videoscene',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='planned', max_length=20),
        ),
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('full_generation', 'Full Generation'), ('scene_regeneration', 'Scene Regeneration'), ('assembly', 'Assembly')], db_index=True, default='full_generation', max_length=30)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('assembling', 'Assembling'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=20)),
                ('current_stage', models.CharField(default='queued', max_length=50)),
                ('total_scenes', models.PositiveIntegerField(default=0)),
                ('completed_scenes', models.PositiveIntegerField(default=0)),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('provider', models.CharField(default='fal_pixverse_c1', max_length=50)),
                ('provider_job_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('reservation_key', models.CharField(blank=True, db_index=True, max_length=160, null=True)),
                ('credits_reserved', models.PositiveIntegerField(default=0)),
                ('credits_consumed', models.PositiveIntegerField(default=0)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=2)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('queued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='video_generator.videoproject')),
                ('target_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regeneration_jobs', to='video_generator.videoscene')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_jobs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_jobs', to='video_generator.workspace')),
            ],
            options={
                'ordering': ['-queued_at'],
            },
        ),
    ]
